apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: microservices.paas.redhat.com
spec:
  group: paas.redhat.com
  names:
    kind: MicroService
    listKind: MicroServiceList
    plural: microservices
    singular: microservice
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
