apiVersion: paas.redhat.com/v1alpha1
kind: MicroService
metadata:
  annotations:
    cert.patrickeasters.com/ipa-managed: 'true'
  name: example-microservice
spec:
  image: "quay.io/redhatit/spring-boot-helloworld"
  hostname: "example-microservice.apps.opsme4.os4-sandbox.paas.redhat.com"
  replicas: 2
